In [1]:
import torch as t
from torch import nn
from torch.autograd import Variable as V
import torch.optim as optim
import os
import pandas as pd

In [2]:
class LSTM(nn.Module):
    def __init__(self,input_feature_dim,hidden_feature_dim,hidden_layer_num,batch_size,classes_num):
        super(LSTM_signal,self).__init__()
        self.input_feature_dim = input_feature_dim
        self.hidden_feature_dim = hidden_feature_dim
        self.hidden_layer_num = hidden_layer_num
        self.batch_size = batch_size 

        #初始化LSTM       
        self.lstm = nn.LSTM(input_feature_dim,hidden_feature_dim,hidden_layer_num)
        #LSTM的輸出藉由單層的線性神經網路層分類~
        self.linear1 = nn.Linear(hidden_feature_dim,classes_num)

    def init_hidden(self):
        h0 = t.randn(self.hidden_layer_num,self.batch_size,self.hidden_feature_dim)
        c0 = t.randn(self.hidden_layer_num,self.batch_size,self.hidden_feature_dim)
    def foward(self, input):
        output,(hn,cn) = self.lstm(input,(h0,c0))
        output= self.linear1(output[-1])         
        return output,(hn,cn)

In [3]:
def mape(y_true, y_pred):
    n = len(y_true)
    mape = sum(np.abs((y_true - y_pred)/y_true))/n*100
    return mape

In [4]:
df = pd.read_csv('FUTURE.csv')

In [5]:
df.head()

,Date,COMEX_Gold_close,COMEX_Gold_open,COMEX_Gold_high,COMEX_Gold_low,COMEX_Gold_volume,LIFFE_Gold_close,LIFFE_Gold_open,LIFFE_Gold_high,LIFFE_Gold_low,...,NYMEX_NaturalGas_open,NYMEX_NaturalGas_high,NYMEX_NaturalGas_low,NYMEX_NaturalGas_volume,NYMEX_Crude_close,NYMEX_Crude_open,NYMEX_Crude_high,NYMEX_Crude_low,NYMEX_Crude_volume,LME_Nickel_close
0,2018-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-01-02,1319.1,1309.1,1320.4,1305.1,18577.0,1312.37,1302.66,1319.01,1302.59,...,3.078,3.097,2.923,24599.0,60.37,60.18,60.74,60.10,25854.0,12655.0
2,2018-01-03,1314.5,1319.0,1323.0,1308.9,26988.0,1316.45,1317.75,1321.56,1307.60,...,3.040,3.056,2.959,17426.0,61.93,60.39,61.97,60.28,26372.0,12450.0
3,2018-01-04,1324.0,1315.5,1327.3,1307.1,29338.0,1319.37,1313.18,1326.07,1305.98,...,3.015,3.070,2.840,24773.0,61.89,61.96,62.21,61.59,27919.0,12640.0
4,2018-01-05,1320.3,1323.9,1324.7,1314.6,28055.0,1318.99,1321.82,1323.47,1313.77,...,2.874,2.887,2.746,18368.0,61.59,61.90,62.04,61.09,25505.0,12545.0

In [6]:
df= df.drop([0])

In [7]:
kw = pd.read_csv('KEYWORD.csv')

In [8]:
df = df.drop(['Date'], axis = 1)
kw = kw.drop(['Date'], axis = 1)

In [9]:
res = df.join(kw)

In [10]:
df.describe(include = 'all')

,COMEX_Gold_close,COMEX_Gold_open,COMEX_Gold_high,COMEX_Gold_low,COMEX_Gold_volume,LIFFE_Gold_close,LIFFE_Gold_open,LIFFE_Gold_high,LIFFE_Gold_low,LME_Lead_close,...,NYMEX_NaturalGas_open,NYMEX_NaturalGas_high,NYMEX_NaturalGas_low,NYMEX_NaturalGas_volume,NYMEX_Crude_close,NYMEX_Crude_open,NYMEX_Crude_high,NYMEX_Crude_low,NYMEX_Crude_volume,LME_Nickel_close
count,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,213.000000,...,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000,214.000000
mean,1277.567130,1278.123611,1284.305556,1271.315741,20982.347222,1275.320273,1275.741264,1283.068611,1268.145370,2302.244131,...,2.885542,2.926116,2.846750,6147.444444,67.242407,67.202546,67.988194,66.371111,36674.337963,13580.537383
std,54.775433,54.627248,55.015426,54.225624,6801.312660,56.000646,56.042856,56.116943,56.153152,210.383722,...,0.193287,0.211360,0.183109,5177.775561,3.822281,3.836711,3.849512,3.778454,15723.620289,886.400150
min,1181.000000,1180.700000,1189.000000,1167.100000,372.000000,1176.580000,1176.380000,1185.900000,1160.390000,1913.000000,...,2.553000,2.589000,2.530000,323.000000,58.950000,58.980000,59.730000,58.070000,729.000000,11530.000000
25%,1222.175000,1223.925000,1229.475000,1217.750000,16918.000000,1219.517500,1221.252500,1226.097500,1211.930000,2083.500000,...,2.743000,2.775250,2.711750,3126.750000,64.395000,64.340000,65.227500,63.557500,30203.000000,12831.250000
50%,1297.700000,1297.600000,1304.800000,1292.650000,20234.000000,1296.505000,1297.315000,1302.060000,1289.690000,2348.000000,...,2.840000,2.881500,2.820000,4431.500000,67.455000,67.465000,68.130000,66.425000,38725.000000,13550.000000
75%,1325.025000,1325.300000,1333.575000,1319.750000,24327.000000,1324.002500,1324.412500,1332.182500,1318.900000,2464.500000,...,2.962500,2.991000,2.930000,7085.750000,69.932500,69.890000,70.447500,68.837500,45036.250000,14017.500000
max,1357.800000,1357.100000,1369.400000,1350.800000,45396.000000,1361.530000,1361.160000,1366.150000,1348.670000,2668.000000,...,3.538000,3.661000,3.410000,26880.000000,76.220000,76.220000,76.900000,74.930000,94150.000000,15755.000000

In [12]:
res.to_csv('Result.csv')